/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminConsoleRouteImport } from './routes/admin-console'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportChildCareRouteImport } from './routes/support.child-care'
import { Route as ApiPublicSeedFirstAdminRouteImport } from './routes/api/public/seed-first-admin'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin-console',
  path: '/admin-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportChildCareRoute = SupportChildCareRouteImport.update({
  id: '/child-care',
  path: '/child-care',
  getParentRoute: () => SupportRoute,
} as any)
const ApiPublicSeedFirstAdminRoute = ApiPublicSeedFirstAdminRouteImport.update({
  id: '/api/public/seed-first-admin',
  path: '/api/public/seed-first-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/trust': typeof TrustRoute
  '/support/child-care': typeof SupportChildCareRoute
  '/api/public/seed-first-admin': typeof ApiPublicSeedFirstAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/trust': typeof TrustRoute
  '/support/child-care': typeof SupportChildCareRoute
  '/api/public/seed-first-admin': typeof ApiPublicSeedFirstAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/trust': typeof TrustRoute
  '/support/child-care': typeof SupportChildCareRoute
  '/api/public/seed-first-admin': typeof ApiPublicSeedFirstAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-console'
    | '/dashboard'
    | '/ledger'
    | '/login'
    | '/reports'
    | '/sitemap.xml'
    | '/support'
    | '/trust'
    | '/support/child-care'
    | '/api/public/seed-first-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-console'
    | '/dashboard'
    | '/ledger'
    | '/login'
    | '/reports'
    | '/sitemap.xml'
    | '/support'
    | '/trust'
    | '/support/child-care'
    | '/api/public/seed-first-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-console'
    | '/dashboard'
    | '/ledger'
    | '/login'
    | '/reports'
    | '/sitemap.xml'
    | '/support'
    | '/trust'
    | '/support/child-care'
    | '/api/public/seed-first-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  DashboardRoute: typeof DashboardRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRouteWithChildren
  TrustRoute: typeof TrustRoute
  ApiPublicSeedFirstAdminRoute: typeof ApiPublicSeedFirstAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-console': {
      id: '/admin-console'
      path: '/admin-console'
      fullPath: '/admin-console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/child-care': {
      id: '/support/child-care'
      path: '/child-care'
      fullPath: '/support/child-care'
      preLoaderRoute: typeof SupportChildCareRouteImport
      parentRoute: typeof SupportRoute
    }
    '/api/public/seed-first-admin': {
      id: '/api/public/seed-first-admin'
      path: '/api/public/seed-first-admin'
      fullPath: '/api/public/seed-first-admin'
      preLoaderRoute: typeof ApiPublicSeedFirstAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SupportRouteChildren {
  SupportChildCareRoute: typeof SupportChildCareRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportChildCareRoute: SupportChildCareRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  DashboardRoute: DashboardRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRouteWithChildren,
  TrustRoute: TrustRoute,
  ApiPublicSeedFirstAdminRoute: ApiPublicSeedFirstAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
